#!/bin/bash

STEP=10
MAX_BRIGHTNESS=100
MIN_BRIGHTNESS=0

CURRENT_BRIGHTNESS=$(brightnessctl get)
BRIGHTNESS_MAX=$(brightnessctl max)
BRIGHTNESS=$(($CURRENT_BRIGHTNESS * 100 / $BRIGHTNESS_MAX))

if [ "$1" == "up" ]; then
    NEW_BRIGHTNESS=$(($BRIGHTNESS + $STEP))
    [ $NEW_BRIGHTNESS -gt $MAX_BRIGHTNESS ] && NEW_BRIGHTNESS=$MAX_BRIGHTNESS
elif [ "$1" == "down" ]; then
    NEW_BRIGHTNESS=$(($BRIGHTNESS - $STEP))
    [ $NEW_BRIGHTNESS -lt $MIN_BRIGHTNESS ] && NEW_BRIGHTNESS=$MIN_BRIGHTNESS
fi

brightnessctl set $(($NEW_BRIGHTNESS * $BRIGHTNESS_MAX / 100))
